### ISSUE TITLE
Configure MySQL Connection with SSL from envvars

### ISSUE THREAD

**Issue by kHRISl33t** [bitnami/bitnami-docker-matomo#21]
Hello,

I couldn't configure MySQL SSL connection from envvars and it looks like its not supported in this docker image, but according to [matomo docs its available](https://matomo.org/faq/how-to-install/faq_26273/). 

If anyone wants to configure matomo with SSL in kubernetes, I managed to do it the following way:

1. Create a persistent disk for matomo and your ssl cert inside your deployment file.
```
volumeMounts:
      - mountPath: /bitnami
         name: matomo-disk
      - mountPath: /etc/mysql-ssl
         name: ssl-mysql-volume
volumes:
      - name: matomo-disk
         persistentVolumeClaim:
           claimName: matomo-persistent-storage-claim
      - name: ssl-mysql-volume
         secret:
           secretName: mysql-ssl
```
2. Start the container and configure it without SSL at first try.
3. Copy the config file from the container `kubectl cp default/matomo_pod:bitnami/matomo/
config/config.ini.php /path/to/copy` to your computer.
4. Edit the file and add:
```
[database]
...yourdbcreds...
enable_ssl = 1
ssl_ca = "/etc/mysql-ssl/cert.pem"
```
5. Copy it back to the container `kubectl cp /path/to/copy default/matomo_pod:bitnami/matomo/
config`
6. Restart your container and it will use SSL connection.

It would be nice to be able to configure the database variable from envvars.
For example: 
`MATOMO_ENABLE_SSL=1`
`MATOMO_SSL_CA=/path/to/cert`

**Comment by marcosbc** [comment]
Hi @kHRISl33t, thanks for the details. We don't currently support secured MySQL (SSL), which is something we might add in the future. For now, I've opened an internal task for documenting this feature.

In addition to that, I've also opened an internal task for adding SSL configuration options to Matomo. In the meantime, we recommend you to mount the "config.ini.php" in order to avoid running the "kubectl cp" command.

**Comment by ylascombe** [comment]
👍

**Comment by marcosbc** [comment]
Hi @ylascombe,

After investigating further, it looks like Matomo open-source may not fully read-only config files: https://forum.matomo.org/t/the-matomo-configuration-file-config-config-ini-php-is-not-writable/30756/3

However, Matomo itself may partially work. But we would need to perform a important changes to the current logic in order to support mounted configuration files from Kubernetes config maps.

The only simple way that I can think of for applying a custom configuration file is for you to create a custom Docker image with these changes:

```
diff --git a/3/debian-10/rootfs/app-entrypoint.sh b/3/debian-10/rootfs/app-entrypoint.sh
index f74825a..e657ff1 100755
--- a/3/debian-10/rootfs/app-entrypoint.sh
+++ b/3/debian-10/rootfs/app-entrypoint.sh
@@ -11,6 +11,7 @@ if [[ "$1" == "nami" && "$2" == "start" ]] || [[ "$1" == "/run.sh" ]]; then
     nami_initialize apache php mysql-client matomo
     info "Starting matomo... "
     . /post-init.sh
+    cp /config.ini.php /opt/bitnami/matomo/config/config.ini.php
 fi

 exec tini -- "$@"
```

And then update the mount path in the chart so it mounts in `/config.ini.php` instead of /bitnami`/matomo/config/config.ini.php`.

**Comment by jobachhu** [comment]
For anyone to this issue in the future, I had the same problem and adapted the solution from #51 to enable SSL:

`Dockerfile`
```
FROM bitnami/matomo:3

COPY init.d /docker-entrypoint-init.d
```

`init.d/02-set-ssl-variables.sh`
```
#!/bin/bash

. /opt/bitnami/base/functions

if [[ "$MATOMO_DATABASE_ENABLE_SSL" =~ ^(yes|Yes|YES)$ ]]; then
  if [[ -f "$MATOMO_DATABASE_SSL_CA_PATH" ]]; then
    info "Configuring SSL connection to database"
    sed -i '/^\[database\]$/a enable_ssl = 1' /opt/bitnami/matomo/config/config.ini.php
    sed -i "/^\[database\]$/a ssl_ca = \"$MATOMO_DATABASE_SSL_CA_PATH\"" /opt/bitnami/matomo/config/config.ini.php
  else
    error "MATOMO_DATABASE_SSL_CA_PATH '$MATOMO_DATABASE_SSL_CA_PATH' must be set and exist when SSL is enabled"
    exit 1
  fi
fi
```

Then adapt your deployment to mount the certificate file from a config map (adapted from test.yaml in this repo - I omitted the other env vars for brevity):
```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: test-matomo
  name: test-matomo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-matomo
  template:
    metadata:
      labels:
        app: test-matomo
    spec:
      containers:
      - image: bitnami/matomo
        name: test-matomo
        env:
        - name: MATOMO_DATABASE_ENABLE_SSL
          value: "yes"
        - name: MATOMO_DATABASE_SSL_CA_PATH
          value: "/etc/ssl/mysql/trusted-ca-cert.crt"
        volumeMounts:
          - name: mysql-ssl
            mountPath: "/etc/ssl/mysql"
            readOnly: true
      volumes:
        - name: mysql-ssl
          secret:
            secretName: matomo-mysql-credentials
            items:
              - key: ssl-ca
                path: trusted-ca-cert.crt
```


One problem I noticed is that if you enable `REQUIRE SSL` for the matomo user after the image started, it will work, but if the image restarts it fails during startup because the image tries to verify that it can connect to the database. Is it possible to configure the mysql client during setup to use SSL as well?

**Comment by marcosbc** [comment]
@jobachhu That's great! As for mysql-client, it seems it currently does not support SSL out-of-the-box in containers, but the functionality is implemented and only requires us to enable a couple of environment variables. We'll try and get the fix applied, letting you know once it's released.

**Comment by kHRISl33t** [comment]
At the moment I'm still using my example (very little maintenance required with that), but it would be nice to finally have this feature @marcosbc! :+1:

**Comment by marcosbc** [comment]
Unfortunately we have not looked into implementing in Matomo yet. However, if there is a workaround you can follow, even better.

@jobachhu We just released a new revision of the container, with a tag of `3.13.4-debian-10-r8`. You can now specify the below environment variables:

* `MYSQL_CLIENT_ENABLE_SSL`: Whether to enable SSL connections for `mysql-client` or not (defaults to "no").
* `MYSQL_CLIENT_SSL_CA_FILE`: Path to the SSL CA file (optional).

**Comment by jobachhu** [comment]
Perfect, thanks for adding those @marcosbc! I added these variables to my deployment and the container starts without issues with `REQUIRE SSL` enabled. The solution with the init script above works well for me with this addition.

Thank you for the help!

**Comment by michael-niemand** [comment]
> For anyone to this issue in the future, I had the same problem and adapted the solution from #51 to enable SSL:

I don't think that works because the /docker-entrypoint.d scripts are called in the post-init.sh script, but the matomo init process needs the SSL connection before that's called

**Comment by michael-niemand** [comment]
When I'm followoing @jobachhu 's steps, (custom Docker with `02-set-ssl-variables.sh` and @marcosbc additional env vars) I still get the following error in the logs; setup does not finish:

```
│     <h2>Database Setup</h2>                                                                                                                                                                                                                                          │
│             <div class="alert alert-danger">                                                                                                                                                                                                                         │
│             Error while trying to connect to the database server:                                                                                                                                                                                                    │
│             SSL connection is required. Please specify SSL options and retry.                                                                                                                                                                                        │
│         </div>    
``` 

When I do a

`watch cat /opt/bitnami/matomo/config/config.ini.php`     

in parallel to following the logs, it appears like Matomo is trying to access the database _before_ `init.d/02-set-ssl-variables.sh` is even executed (it's called at the end in `post-init.sh`), so this can't work as far as I understand it. Can someone point me in the right direction? Mysql-clients connection does seem to work. It's only matomo's config that's making trouble.

**Comment by michael-niemand** [comment]
I tried all sorts of variants now but I can't get it to work on initial install using mysql over ssl. 

The config.ini.php is generated during nami_initialize matomo, which at the same time needs the [database] section including the ssl parameters. Only solution I could think of is a script that loops, trying to find `config.ini.php` and then tries to insert the `[database]` section with `enable_ssl = 1` as soon as the file gets created but that's hella dirty. 

Another idea would be to deactivate ssl and reactivate after installation using the cloud providers API but that's even dirtier. 

There has to be a better way

**Comment by marcosbc** [comment]
Hi @michael-niemand, the solution would involve adding support for SSL in the logic for initializing Matomo. That can be found in the following path inside the container (refer to nami.json, main.js and helpers.js):

    /root/.nami/components/com.bitnami.matomo

Unfortunately we have not started looking into this yet since we have a lot of things on our plate. However it looks like a simple change so I'll try to change it in the incoming days and see if it can be published soon.

If you find any similar suggestions for improving the container, feel free to contribute by improving the logic and send us the diffs via a comment in the specific issue, or in a Gist, we'd be glad to review those contributions.

For the longer term, we're expected to re-implement the initialization logic in Bash and publish the source code in GitHub in a `rootfs` directory (find an example [here](https://github.com/bitnami/bitnami-docker-drupal/tree/master/9/debian-10/rootfs)), which would make it a lot easier to contribute for. However we have not started that work for Matomo yet, and due to the winter vacations period, it will likely not happen before 2021.

**Comment by michael-niemand** [comment]
thanks for the comprehensive answer, appreciate it. I will have a look at the code but I'm afraind I won't be of much help. I'm more on the infrastructure side of things - just happens  that I was tasked with deploying Matomo on k8s using a managed DB that requires ssl ...

**Comment by marcosbc** [comment]
Hi @michael-niemand, we're working on releasing this feature via the environment variable `MATOMO_ENABLE_DATABASE_SSL`. If you set that value, the configuration file will be configured to add `enable_ssl = 1` in the `[database]` section.

We expect this to appear in the `3.14.1-debian-10-r34` container image, which will most probably be released later today. Once published, you will also see the environment variable appear here: https://github.com/bitnami/bitnami-docker-matomo#environment-variables

**Comment by marcosbc** [comment]
Hi, we just released `3.14.1-debian-10-r35` with this feature. Deploy a clean install with `MATOMO_ENABLE_DATABASE_SSL=yes` and the following content should appear in Matomo's `config.ini.php` file:

```ini
[database]
...
enable_ssl=1
```

**Comment by michael-niemand** [comment]
Amazing! Can't wait to update first thing tomorrow morning. Much obliged!

**Comment by michael-niemand** [comment]
@marcosbc 
I'm still getting 

`Error while trying to connect to the database server:                                                                                                                                                                                                    SSL connection is required. Please specify SSL options and retry.`
 
what is being set as CA certificate? The value for mysql `MYSQL_CLIENT_SSL_CA_FILE` ? I also pass `MATOMO_DATABASE_SSL_CA_PATH` with the proper path from @jobachhu's reply.

these are all the env vars the container has (some sanitized for obv. reasons):

```
_=/usr/bin/env
ALLOW_EMPTY_PASSWORD=no
APACHE_ENABLE_CUSTOM_PORTS=no
APACHE_HTTP_PORT_NUMBER=80
APACHE_HTTPS_PORT_NUMBER=443
BITNAMI_APP_NAME=matomo
BITNAMI_IMAGE_VERSION=3.14.1-debian-10-r35
DEV_MATOMO_PORT_80_TCP_ADDR=10.2.13.174
DEV_MATOMO_PORT_80_TCP_PORT=80
DEV_MATOMO_PORT_80_TCP_PROTO=tcp
DEV_MATOMO_PORT_80_TCP=tcp://10.2.13.174:80
DEV_MATOMO_PORT=tcp://10.2.13.174:80
DEV_MATOMO_SERVICE_HOST=10.2.13.174
DEV_MATOMO_SERVICE_PORT_HTTP=80
DEV_MATOMO_SERVICE_PORT=80
HOME=/root
HOSTNAME=dev-matomo-7d9548865d-h9kkd
KUBERNETES_PORT_443_TCP_ADDR=10.2.13.1
KUBERNETES_PORT_443_TCP_PORT=443
KUBERNETES_PORT_443_TCP_PROTO=tcp
KUBERNETES_PORT_443_TCP=tcp://10.2.13.1:443
KUBERNETES_PORT=tcp://10.2.13.1:443
KUBERNETES_SERVICE_HOST=10.2.13.1
KUBERNETES_SERVICE_PORT_HTTPS=443
KUBERNETES_SERVICE_PORT=443
MARIADB_HOST=sql-server.requireing.ssl.com
MARIADB_PORT_NUMBER=3306
MARIADB_ROOT_PASSWORD=
MARIADB_ROOT_USER=root
MATOMO_DATABASE_NAME=dev-matomo
MATOMO_DATABASE_PASSWORD=superSecretDbPassword
MATOMO_DATABASE_SSL_CA_PATH=/etc/ssl/mysql/trusted-ca-cert.crt
MATOMO_DATABASE_USER=matomo@sql-server
MATOMO_EMAIL=web@our-company.com
MATOMO_ENABLE_DATABASE_SSL=yes
MATOMO_ENABLE_PROXY_URI_HEADER=no
MATOMO_HOST=analytics.web01.our.company.com
MATOMO_PASSWORD=My$uper$ecretPassword113#
MATOMO_USERNAME=admin
MATOMO_WEBSITE_HOST=https://site.com
MATOMO_WEBSITE_NAME=Site Prod
MYSQL_CLIENT_CREATE_DATABASE_NAME=
MYSQL_CLIENT_CREATE_DATABASE_PASSWORD=
MYSQL_CLIENT_CREATE_DATABASE_PRIVILEGES=ALL
MYSQL_CLIENT_CREATE_DATABASE_USER=
MYSQL_CLIENT_ENABLE_SSL=yes
MYSQL_CLIENT_SSL_CA_FILE=/etc/ssl/mysql/trusted-ca-cert.crt
NAMI_DEBUG=true
OS_ARCH=amd64
OS_FLAVOUR=debian-10
OS_NAME=linux
PATH=/opt/bitnami/php/bin:/opt/bitnami/php/sbin:/opt/bitnami/apache/bin:/opt/bitnami/mysql/bin:/opt/bitnami/common/bin:/opt/bitnami/nami/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
PHP_MEMORY_LIMIT=118M
PWD=/
SHLVL=1
SMTP_AUTH=Plain
SMTP_HOST=
SMTP_PASSWORD=
SMTP_PORT=
SMTP_PROTOCOL=
SMTP_USER=
TERM=xterm

```

**Comment by javsalgar** [comment]
Hi,

Do you see the enable_ssl parameter? Note that you may need to do a fresh deployment in order for the settings to be set

```
[database]
...
enable_ssl=1
```

**Comment by michael-niemand** [comment]
@javsalgar I did a `watch cat /opt/bitnami/matomo/config/config.ini.php` to see what is being generated but the container is being destroyed before the file is created or at least right in that moment - Thus I didnt see if that part is written. But I can maybe try a different method to find out

**Comment by michael-niemand** [comment]
I was able to catch the moment the file is being created.
It's contents are:

```
[General]
force_ssl=1
enable_trusted_host_check=0
```

**Comment by javsalgar** [comment]
Hi,

This is strange, the line should be `enable_ssl`, don't you see any line in a database section?

**Comment by michael-niemand** [comment]
the container crashes with the error below -  right after the config.ini.php is created, and at that point the `[General]` section is all that has been written to the config file:
![image](https://user-images.githubusercontent.com/12845693/95962210-5c88e480-0e06-11eb-9b72-4b7872357d4e.png)

**Comment by michael-niemand** [comment]
... btw: Not doing the changes from the comments
https://github.com/bitnami/bitnami-docker-matomo/issues/21#issuecomment-592434338 
or 
https://github.com/bitnami/bitnami-docker-matomo/issues/21#issuecomment-607119312
in this deployment, but using the official version (r39 as of now). I can provide you with additional information if you so require. Logs, parameters ... just tell me what you need

**Comment by javsalgar** [comment]
Could you provide me with the full logs? It seems that something failed during the installation wizard as the tables were not created.

**Comment by michael-niemand** [comment]
sure, there you go: https://gist.github.com/michael-niemand/000e92d827576f4e046ea3c335395a9c

**Comment by javsalgar** [comment]
Hi,

Looking at the logs, I see that the Matomo wizard is crashing at some point (note the 500 errors), that would prevent the database from being created. That may be related with the connection to the database. Just to confirm, are you able to have the container running when using a non-SSL database? I want to discard it is an issue with the container environment.

**Comment by michael-niemand** [comment]
Asked ops to deactivate SSL enforcing on the MariaDB server and Matomo was immediately installed.

**Comment by javsalgar** [comment]
Hi,

Thanks for the information, I will forward this for evaluation.

**Comment by michael-niemand** [comment]
@javsalgar Are there any news on this? I really don't want to bother you too much, but we need to decide if we wait for this or find a different solution for now. Thanks you!

**Comment by marcosbc** [comment]
Hi @michael-niemand, unfortunately we haven't had any time to look into this in the recent days. However, we will continue investigating with the hope to have this fixed before end of this week. Would that work for you?

I'm thinking this is happening because the Matomo wizard populates the configuration file without the SSL options, and the flag we enabled is configured to do so after passing the wizard.

In the meantime, unless you are automating the deployment of a Matomo site, you should be able to install Matomo without SSL enforcement, modifying the configuration manually and then enabling enforcement. Since the configuration file is persisted, you shouldn't have to worry about losing the SSL setting.

**Comment by michael-niemand** [comment]
Hi @marcosbc, thank you that would be amazing! Unfortunately we're completely automating the deployment (on kubernetes) and would need to write a ticket to out ops team to disable SSL for the managed DB with each deployment so this workaround would not be an option for us. But if you manage to look into this I would be super grateful. Thanks again, much obliged.

**Comment by marcosbc** [comment]
Hi @michael-niemand, we have just released Matomo `3.14.1-debian-10-r61` with revised SSL support. You can find the newly added flags in the [Environment Variables](https://github.com/bitnami/bitnami-docker-matomo#environment-variables) section:

>* MATOMO_SKIP_BOOTSTRAP: Whether to perform initial bootstrapping for the application. Default: no
>* MATOMO_ENABLE_DATABASE_SSL: Whether to enable SSL for database connections in the Matomo configuration file. Default: no
>* MATOMO_DATABASE_SSL_CA_FILE: Path to the database server CA bundle file. No defaults.
>* MATOMO_DATABASE_SSL_CERT_FILE: Path to the database client certificate file. No defaults.
>* MATOMO_DATABASE_SSL_KEY_FILE: Path to the database client certificate key. No defaults.
>* MATOMO_VERIFY_DATABASE_SSL: Whether to verify the database SSL certificate when SSL is enabled. Default: yes

Due to Matomo limitations, it is required to first install Matomo without SSL ([link](https://matomo.org/faq/how-to-install/faq_26273/), and then to enable SSL or migrate the database to a SSL-enabled server. However, to avoid having to ask your sysadmins to disable/re-enable SSL, you could do the following by making use of the newly added `MATOMO_SKIP_BOOTSTRAP` flag:

* Install to a local MariaDB database (i.e. using the default docker-compose).
* Export the database from your local database server (i.e. `mysqldump -u root bitnami_matomo > bitnami_matomo.sql`)
* In your SSL-enabled database server, create the `bitnami_matomo` database and import the contents (i.e. `mysql --ssl=true -h SERVER -u USER -pPASSWORD bitnami_matomo < bitnami_matomo.sql`)
* Deploy with the newly supported `MATOMO_SKIP_BOOTSTRAP` environment variable (in order not to re-initialize the database).

I was successfully able to connect with an Azure Database for MySQL with SSL enabled by following those steps. The first Matomo installation was done to a local MariaDB database via the [original docker-compose](https://github.com/bitnami/bitnami-docker-matomo/blob/master/docker-compose.yml), then I migrated the database manually to Azure. I used the following docker-compose:

```
version: '2'
services:
  matomo:
    image: 'docker.io/bitnami/matomo:3-debian-10'
    environment:
      - MARIADB_HOST=HOSTNAME.mysql.database.azure.com
      - MARIADB_PORT_NUMBER=3306
      - MATOMO_DATABASE_USER=USERNAME@HOSTNAME
      - 'MATOMO_DATABASE_PASSWORD=PASSWORD
      - MATOMO_DATABASE_NAME=bitnami_matomo
      - ALLOW_EMPTY_PASSWORD=yes
      - MATOMO_SKIP_BOOTSTRAP=yes
      - MATOMO_ENABLE_DATABASE_SSL=yes
      - MATOMO_VERIFY_DATABASE_SSL=no
      - MATOMO_DATABASE_SSL_CA_FILE=/tmp/ca.crt
      - MYSQL_CLIENT_ENABLE_SSL=yes
      - MYSQL_CLIENT_SSL_CA_FILE=/tmp/ca.crt
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - './ca.crt:/tmp/ca.crt'
      - 'matomo_data:/bitnami'
volumes:
  matomo_data:
    driver: local
```

In my case, I also had to mount Azure Database's CA certificate to the container (it can be downloaded from the Web) and had to disable certificate verification as it does not provide any cert/key pair. Other vendors such as AWS RDS may offer those certificates so you would have to add `MATOMO_DATABASE_SSL_CERT_FILE` and `MATOMO_DATABASE_SSL_KEY_FILE`, and remove `MATOMO_VERIFY_DATABASE_SSL`.

I hope it works for you!

**Comment by michael-niemand** [comment]
I think I can make that work. I will try implementing this and give you feedback. Thanks again.

**Comment by michael-niemand** [comment]
Just in case anyone comes here later via search engine, this is how we do it:

1.  run the default docker-compose with a job on our build server
2.  once the log says "matomo successfully initialized", dump the database into a file
3.  build a tiny init container with that dump file and a mysql client
4.  use that init container within the Kubernetes deployment to initialize the DB and then start Matomo using the `MATOMO_SKIP_BOOTSTRAP ` flag

I'm not quite done yet but I'm quite confident this will work nicely.

**Comment by marcosbc** [comment]
I'm glad to see you are figuring out!

As for initializing the database, if you were using the Bitnami MySQL/MariaDB Docker images you could always use the [initdb scripts functionality](https://github.com/bitnami/bitnami-docker-mariadb#initializing-a-new-instance). For charts this is also possible ([link](https://github.com/bitnami/charts/tree/master/bitnami/mariadb#initialize-a-fresh-instance)).

**Comment by michael-niemand** [comment]
Interesting, I will look into it. Thanks again, appreciate it.
