### ISSUE TITLE
Github latest release is not correct

### ISSUE THREAD

**Issue by dawidmalina** [bitnami/bitnami-docker-matomo#64]
**Description**

**Steps to reproduce the issue:**

1. Go to the github.com main project page and verify latest release. You will see that latest version is: `3.7.0-ol-7-r0 release`.
2.Go to project releases page. You will see that latest release is: `4.0.4-debian-10-r1`

**Describe the results you expected:**

Expected results is that main page will show `4.0.4-debian-10-r1` as a latest release.

Additional drawback of this is lack of github notifications about new releases.

**Comment by tommy-b-10** [comment]
I am experiencing the same issue. My UnRaid docker reverted itself from 4.0.4 to 3.7.0 when updating.

**Comment by juan131** [comment]
Hi @tommy-b-10 @dawidmalina 

Thanks so much for reporting this issue! We detected our internal metadata was pointing to the wrong branch. We're fixing it and we'll release a new version fixing the tags so they point to the right branch.

I also created this PR to remove the branch 3 from the repo: https://github.com/bitnami/bitnami-docker-matomo/pull/65

> Note: We highly recommend avoid using rolling tags on production environments. Find more information on [this link](https://docs.bitnami.com/tutorials/understand-rolling-tags-containers/).

**Comment by juan131** [comment]
Hi @tommy-b-10 @dawidmalina 

I just want to let you know that the issue was solved. Thanks again for reporting it!

```console
$ docker pull bitnami/matomo:latest
$ docker run --rm bitnami/matomo:latest -- bash -c "env | grep BITNAMI_IMAGE_VERSION"
...

BITNAMI_IMAGE_VERSION=4.0.4-debian-10-r3
```

**Comment by dawidmalina** [comment]
Hi @juan131 i still see that latest github release points to the old one. Can you also fix that?

**Comment by juan131** [comment]
Fixed @dawidmalina 

But please note that we're not using GitHub releases anymore. We're tagging every revision commit but without doing an actual GH release automatically.

**Comment by dawidmalina** [comment]
Thank you @juan131 - I understand - I would try to figured out how I can be notified in case of the new tag version is available as in this case we can't use github release watching feature.
